APPENV: "DOCKER"
HOME: "/home/vcap/app"
MEMORY_LIMIT: "512m"
PWD: "/home/vcap"
TMPDIR: "/home/vcap/tmp"
USER: "vcap"
VCAP_SERVICES:
  user-provided:
    - name: "fetch"
      credentials:
        port: 8888
  s3:
    - label: "s3"
      provider: "minio-local"
      plan: "basic"
      name: "fetch"
      tags:
        - "AWS"
        - "S3"
        - "object-storage"
      # These are random UUID4s from the Unix `uuid` command
      instance_guid: "d77a8446-2285-4489-8f92-5f0e32e272ab"
      binding_guid: "e686ea8d-4bf4-4c8e-8a43-d69256364bca"
      binding_name: null
      instance_name: "fetch-storage"
      credentials:
        uri: "http://minio:9000"
        port: 9000
        insecure_skip_verify: false
        access_key_id: "nutnutnut"
        secret_access_key: "nutnutnut"
        region: "us-east-1"
        bucket: "fetch"
        endpoint: "http://minio:9000"
        fips_endpoint: "http://minio:9000"
        additional_buckets: []
      syslog_drain_url: "https://ALPHA.drain.url"
      volume_mounts: ["no_mounts"]
  aws-rds:
    - label: "queue-db"
      provider: null
      plan: null
      name: "queue-db"
      tags:
        - "AWS"
        - "RDS"
        - "Postgres"
      instance_guid: "a994b2e4-947c-11ef-bbb9-cf99a893118f"
      binding_guid: "b3c7a0be-947c-11ef-b61f-077373830f35"
      binding_name: null
      instance_name: "queue-db"
      credentials:
        db_name: "postgres"
        host: "queue-db"
        name: "postgres"
        password: ""
        port: 5432
        uri: "postgresql://postgres@queue-db:5432/postgres?sslmode=disable"
        username: "postgres"
      syslog_drain_url: "https://BRAVO.drain.url"
      volume_mounts: ["no_mounts"]